import { Treino } from '../types'
import { mockExercicios } from './exercicios'

export const mockTreinos: Treino[] = [
  {
    id: 'treino-1',
    personalId: 'personal-1',
    alunoId: 'aluno-1',
    nome: 'Treino A - Peito e Tríceps',
    descricao: 'Treino focado em desenvolvimento de peitoral e tríceps',
    exercicios: [
      {
        id: 'te-1',
        exercicioId: 'ex-2',
        exercicio: mockExercicios.find(e => e.id === 'ex-2')!,
        series: 4,
        repeticoes: 10,
        carga: 60,
        descanso: 90,
        ordem: 1,
      },
      {
        id: 'te-2',
        exercicioId: 'ex-11',
        exercicio: mockExercicios.find(e => e.id === 'ex-11')!,
        series: 3,
        repeticoes: 12,
        carga: 50,
        descanso: 90,
        ordem: 2,
      },
      {
        id: 'te-3',
        exercicioId: 'ex-7',
        exercicio: mockExercicios.find(e => e.id === 'ex-7')!,
        series: 3,
        repeticoes: 12,
        carga: 25,
        descanso: 60,
        ordem: 3,
      },
      {
        id: 'te-4',
        exercicioId: 'ex-18',
        exercicio: mockExercicios.find(e => e.id === 'ex-18')!,
        series: 3,
        repeticoes: 15,
        carga: 15,
        descanso: 60,
        ordem: 4,
      },
    ],
    dataCriacao: '2024-12-07T10:00:00Z',
    dataAtribuicao: new Date().toISOString(),
    ativo: true,
  },
  {
    id: 'treino-2',
    personalId: 'personal-1',
    alunoId: 'aluno-1',
    nome: 'Treino B - Pernas',
    descricao: 'Treino completo para pernas e glúteos',
    exercicios: [
      {
        id: 'te-5',
        exercicioId: 'ex-1',
        exercicio: mockExercicios.find(e => e.id === 'ex-1')!,
        series: 4,
        repeticoes: 12,
        carga: 0,
        descanso: 90,
        ordem: 1,
      },
      {
        id: 'te-6',
        exercicioId: 'ex-5',
        exercicio: mockExercicios.find(e => e.id === 'ex-5')!,
        series: 3,
        repeticoes: 15,
        carga: 100,
        descanso: 90,
        ordem: 2,
      },
      {
        id: 'te-7',
        exercicioId: 'ex-9',
        exercicio: mockExercicios.find(e => e.id === 'ex-9')!,
        series: 3,
        repeticoes: 12,
        carga: 40,
        descanso: 60,
        ordem: 3,
      },
      {
        id: 'te-8',
        exercicioId: 'ex-10',
        exercicio: mockExercicios.find(e => e.id === 'ex-10')!,
        series: 3,
        repeticoes: 15,
        carga: 30,
        descanso: 60,
        ordem: 4,
      },
    ],
    dataCriacao: '2024-12-06T10:00:00Z',
    dataAtribuicao: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    ativo: true,
  },
  {
    id: 'treino-3',
    personalId: 'personal-1',
    alunoId: 'aluno-1',
    nome: 'Treino C - Costas e Bíceps',
    descricao: 'Treino para desenvolvimento das costas e bíceps',
    exercicios: [
      {
        id: 'te-9',
        exercicioId: 'ex-3',
        exercicio: mockExercicios.find(e => e.id === 'ex-3')!,
        series: 4,
        repeticoes: 10,
        carga: 50,
        descanso: 90,
        ordem: 1,
      },
      {
        id: 'te-10',
        exercicioId: 'ex-13',
        exercicio: mockExercicios.find(e => e.id === 'ex-13')!,
        series: 3,
        repeticoes: 12,
        carga: 0,
        descanso: 90,
        ordem: 2,
      },
      {
        id: 'te-11',
        exercicioId: 'ex-6',
        exercicio: mockExercicios.find(e => e.id === 'ex-6')!,
        series: 3,
        repeticoes: 12,
        carga: 20,
        descanso: 60,
        ordem: 3,
      },
      {
        id: 'te-12',
        exercicioId: 'ex-17',
        exercicio: mockExercicios.find(e => e.id === 'ex-17')!,
        series: 3,
        repeticoes: 15,
        carga: 15,
        descanso: 60,
        ordem: 4,
      },
    ],
    dataCriacao: '2024-12-05T10:00:00Z',
    dataAtribuicao: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    ativo: true,
  },
  {
    id: 'treino-4',
    personalId: 'personal-1',
    alunoId: 'aluno-2',
    nome: 'Treino Full Body',
    descricao: 'Treino completo para corpo inteiro',
    exercicios: [
      {
        id: 'te-13',
        exercicioId: 'ex-1',
        exercicio: mockExercicios.find(e => e.id === 'ex-1')!,
        series: 3,
        repeticoes: 15,
        carga: 0,
        descanso: 60,
        ordem: 1,
      },
      {
        id: 'te-14',
        exercicioId: 'ex-2',
        exercicio: mockExercicios.find(e => e.id === 'ex-2')!,
        series: 3,
        repeticoes: 12,
        carga: 40,
        descanso: 90,
        ordem: 2,
      },
      {
        id: 'te-15',
        exercicioId: 'ex-8',
        exercicio: mockExercicios.find(e => e.id === 'ex-8')!,
        series: 3,
        repeticoes: 20,
        carga: 0,
        descanso: 30,
        ordem: 3,
      },
    ],
    dataCriacao: '2024-12-07T10:00:00Z',
    dataAtribuicao: new Date().toISOString(),
    ativo: true,
  },
]

